meta_title: "Learning Languages with Youtube"
meta_description: "Learn Languages with Youtube To find out if a video is adapted to your language level, enter the url from youtube in the search bar. You can also browse in our the list below to find viedos classed with language levels."
meta_image: "meta_image.png" # should exist in `app/assets/images/`

